# Generated by Django 3.2.24 on 2024-02-27 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id_utilizator', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=500)),
                ('prenume', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NoteBac',
            fields=[
                ('id_note_bac', models.AutoField(primary_key=True, serialize=False)),
                ('tip_nota1', models.CharField(max_length=500)),
                ('valoare_nota1', models.FloatField()),
                ('tip_nota2', models.CharField(max_length=500)),
                ('valoare_nota2', models.FloatField()),
                ('tip_nota3', models.CharField(max_length=500)),
                ('valoare_nota3', models.FloatField()),
                ('tip_nota4', models.CharField(max_length=500)),
                ('valoare_nota4', models.FloatField()),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.utilizator')),
            ],
        ),
        migrations.CreateModel(
            name='IntrebariChestionar',
            fields=[
                ('id_intrebari_chestionar', models.AutoField(primary_key=True, serialize=False)),
                ('text_intrebare', models.CharField(max_length=500)),
                ('coloana', models.IntegerField()),
                ('punctaj', models.IntegerField()),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.utilizator')),
            ],
        ),
    ]
