# Generated by Django 5.0.2 on 2024-03-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrebarichestionar',
            name='coloana',
        ),
        migrations.RemoveField(
            model_name='intrebarichestionar',
            name='punctaj',
        ),
        migrations.RemoveField(
            model_name='intrebarichestionar',
            name='utilizator',
        ),
    ]
