# Generated by Django 5.0.2 on 2024-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_raspunsuri'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrebarichestionar',
            name='categorie',
            field=models.CharField(default='Categorie implicită', max_length=100),
        ),
    ]
